### ISSUE TITLE
Test from file fails

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/pyuvsim#7]
Running the test_single_source_vis_uvdata yields the following result:

Looks like there is a parameter mis-typed in the test file.

```(HERA) matthew@cosmos:~/src/pyuvsim/pyuvsim (master)$ nosetests tests/test_uvsim.py:test_single_source_vis_uvdata
E
======================================================================
ERROR: test_uvsim.test_single_source_vis_uvdata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matthew/anaconda/envs/HERA/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/matthew/work/src/pyuvsim/pyuvsim/tests/test_uvsim.py", line 52, in test_single_source_vis_uvdata
    hera_uv.read_uvfits(EW_uvfits_file)
  File "/home/matthew/anaconda/envs/HERA/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvdata.py", line 1295, in read_uvfits
    run_check_acceptability=run_check_acceptability)
  File "/home/matthew/anaconda/envs/HERA/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvfits.py", line 301, in read_uvfits
    run_check_acceptability=run_check_acceptability)
  File "/home/matthew/anaconda/envs/HERA/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvdata.py", line 333, in check
    run_check_acceptability=run_check_acceptability)
  File "/home/matthew/anaconda/envs/HERA/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvbase.py", line 262, in check
    '. Should be: ' + str(param.expected_type))
ValueError: UVParameter _channel_width is not the appropriate type. Is: <type 'int'>. Should be: <type 'float'>

----------------------------------------------------------------------
Ran 1 test in 1.033s

FAILED (errors=1)
```

**Comment by dannyjacobs** [comment]
Fixed by a pyuvdata update. PR submitted by Jonnie

**Comment by dannyjacobs** [comment]
PR fix is merged in pyuvdata _and_ the test file is fixed to avoid it anyway.
